version: '3.8'

services:
  vyanexus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vyanexus_app
    restart: always
    env_file:
      - .env.production
    expose:
      - "3000"
    volumes:
      - /var/www/vyanexus/tenants:/var/www/vyanexus/tenants # Mapeamento para volumes NVMe
      - ./public/uploads:/app/public/uploads
    depends_on:
      - mysql
    networks:
      - vyanexus_net

  nginx:
    image: nginx:latest
    container_name: vyanexus_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro # Para configurações de SSL/domínio
      - /var/www/vyanexus/tenants:/var/www/vyanexus/tenants # Mapeamento para volumes NVMe
    depends_on:
      - vyanexus
    networks:
      - vyanexus_net

  mysql:
    image: mysql:8.0
    container_name: vyanexus_mysql
    restart: always
    env_file:
      - .env.production
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-5camisaNexus}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-vya_nexus}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-5camisaNexus}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vyanexus_net

networks:
  vyanexus_net:
    driver: bridge

volumes:
  mysql_data:
